#!/usr/bin/python
"""
Copyright (c) Abel Deuring 2006 <adeuring@gmx.net>

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

"""
import sys
import gtk
from Eikazo import Eikazo, Widgets, I18n

t = I18n.get_translation('eikazo')
if t:
    _ = t.gettext
else:
    _ = lambda x: x

dev = Widgets.getDevice()
if dev == 0:
    errmsg = gtk.MessageDialog(None, gtk.DIALOG_MODAL,
                gtk.MESSAGE_ERROR, gtk.BUTTONS_CLOSE, 
                _("eikazo: no scanners found"))
    errmsg.run()
    errmsg.destroy()
if not dev:
    sys.exit(1)
    
m = Eikazo.SaneMainWindow(dev, type=gtk.WINDOW_TOPLEVEL)
m.main()
